[template]
src="leo_manager_master.tmpl"
dest="/opt/leofs/leo_manager_0/etc/leo_manager.conf"
owner="root"
mode="644"
keys=[
  "/leofs/manager/master_ip",
  "/leofs/manager/slave_ip",
  "/leofs/manager/num_replicas",
  "/leofs/manager/read",
  "/leofs/manager/write",
  "/leofs/manager/delete",
  "/leofs/manager/rack_aware_replicas",
  "/leofs/manager/mnesia_dir",
  "/leofs/manager/master_log_level",
  "/leofs/manager/dc_id",
  "/leofs/manager/cluster_id",
  "/leofs/distributed_cookie"
]
watch=true
interval=120
reload_cmd="/opt/leofs/leo_manager_0/bin/leo_manager stop; /opt/leofs/leo_manager_0/bin/leo_manager start"
