[template]
src="leo_gateway.tmpl"
dest="/opt/leofs/leo_gateway/etc/leo_gateway.conf"
owner="root"
mode="644"
keys=[
  "/leofs/manager/master_ip",
  "/leofs/manager/slave_ip",
  "/leofs/distributed_cookie",
]
watch=true
reload_cmd="/opt/leofs/leo_gateway/bin/leo_gateway stop; /opt/leofs/leo_gateway/bin/leo_gateway start"
